# This is a basic workflow to help you get started with Actions
# reference: 
# https://github.com/intel-innersource/frameworks.ai.infrastructure.argonne-onesource/blob/master/.github/workflows/ci.yml
# cheet sheet:
# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.html
name: Tmp trial
# Controls when the workflow will run
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule 
on:
  workflow_dispatch:
    inputs:
      gha_runner:
        type: choice
        description: Where to run the GHA job?
        options:
        - "pytorch"            
env:
  node_proxy: 'http://proxy-us.intel.com:911'
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"


  Preparation:
    # The type of runner that the job will run on
    runs-on: ["${{ inputs.gha_runner }}" ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Print and prepare config file
        id: get_env_data
        run: | 
          set -x
          if [ -z ${{ inputs.Config_File }}  ]; then
            echo "Please provide config file path! E.g. /home/huxue/ioh_validation_gha/weekly_configs/1n_xpu_3.10.yml"
            exit 1
          else
            Config_File=${{ inputs.Config_File }}
          fi          
          content=`cat ${Config_File}` || true
          python3 ./scripts/common/parse_config.py --file $Config_File > env_var_config.sh
          bash env_var_config.sh
 
      - name: Update env vars
        run: |
          bash ./scripts/common/prepare_gha_work_envs.sh
          bash env_var_config.sh
          echo Redownload_ITEX_Model_Repo: $Redownload_ITEX_Model_Repo
 
      - name: Clone Model Repository
        if:  env.Redownload_ITEX_Model_Repo == 'True'
        run: | 
          echo "Cloning model repository"
          echo Redownload_ITEX_Model_Repo: $Redownload_ITEX_Model_Repo
